requires 'common::sense';
requires 'IO::Handle';
requires 'IO::Socket::Socks';
requires 'IO::Socket::SSL';
requires 'LWP::UserAgent';
requires 'Mojo::UserAgent';
requires 'Moo';
requires 'Test::Pretty';
requires 'URI';
